stages:
  - test

test_windows_job:
  stage: test
  tags: 
    - windows
  only:
    - master
  script: 
    - chcp 65001
    - cd "%CI_PROJECT_DIR%"
    - call run-test.cmd
  artifacts:
    paths:
      - publish

test_linux_job:
  stage: test
  tags: 
    - linux
  only:
    - master
  script: 
    - cd "$CI_PROJECT_DIR"
    - sh run-test.sh
  artifacts:
    paths:
      - publish
